server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for Result Service
        - id: result-service
          uri: lb://result-service
          predicates:
            - Path=/api/results/**
          filters:
            - StripPrefix=0

        # Route for Question Bank Service  
        - id: question-bank-service
          uri: lb://question-bank-service
          predicates:
            - Path=/api/question-banks/**
          filters:
            - StripPrefix=0

        # Route for Main Backend (Quiz Management)
        - id: quiz-backend
          uri: lb://quiz-platform
          predicates:
            - Path=/api/quiz/**, /api/auth/**, /api/admin/**
          filters:
            - StripPrefix=0

      # Global CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:5173"  
              - "http://localhost:5174"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

      # Default filters for all routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG